### ISSUE TITLE
Assert file is executable

### ISSUE THREAD

**Issue by peter279k** [adhocore/asserts#11]
## Introduction

This is about the executable file assertion.

According to the latest [PHPUnit doc](https://phpunit.readthedocs.io/en/latest/assertions.html?highlight=assert%20file), PHPUnit provides the `assertFileEquals`, `assertFileExists`, `assertFileIsWritable`, and `assertFileIsReadable`.

I think we should implement the `assertFileIsExecutable`.

- [ ] Bug/Issue
- [X] Feature request
- [ ] General stuff

**Comment by adhocore** [comment]
yes ;)

**Comment by peter279k** [comment]
It should be closed via PR #14.

**Comment by adhocore** [comment]
actually in PR description if you put `closes #11` then the issue is closed automatically when the pr gets merged
