### ISSUE TITLE
Asserts::assertFloatEquals bcmath extension

### ISSUE THREAD

**Issue by peter279k** [adhocore/asserts#2]
## Introduction

**This is a**

- [X] Feature request

According to the `Asserts::assertFloatEquals` method, it looks like this will use `bccomp` if we have the `bcmath` extension.

I think we should use the `suggest` block to make this `bcmath` extension optional in `composer.json`.

**Comment by adhocore** [comment]
yes nice idea. thanks for filing the issue :)
